spring:
  profiles:
    active: dev
  application:
    name: find-friend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/findfriend?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  session:
    #失效时间（分钟）两个月
    timeout: 86400
    store-type: redis
  # redis配置
  redis:
    port: 6379
    host: localhost
    database: 0
#sprintboot2.6以上
#  mvc:
#    pathmatch:
#      matchint-strategy: ANT_PATH_MATCHER
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0