spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/findfriend?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  session:
    timeout: 86400
server:
  address: 0.0.0.0
